version: '3.4'

services:
  fluentd:
    build:
      context: ./fluentd/
    expose:
      - '24224'
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    links:
      - 'elasticsearch'
    networks:
      default: {}
      docker-monitoring:
        aliases: [fluentd]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    expose:
      - '9200'
    ports:
      - '9200:9200'
    networks:
      default: {}
      docker-monitoring:


  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    links:
      - 'elasticsearch'
    ports:
      - '5601:5601'

networks:
  docker-monitoring:
    external: true